spring:
  cassandra:
    keyspace-name: plankton
    username: cassandra
    password: cassandra
    local-datacenter: dc1

springdoc:
  use-management-port: true

management:
  endpoints:
    web:
      exposure:
        include: health, openapi, swagger-ui, databases
  server:
    port: 9090